<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
### Hidden Layer:
### Output Layer:
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [3]:
df['bias'] = 1
df.head()

x1  x2  y  bias
0   0   0  1     1
1   1   0  1     1
2   0   1  1     1
3   1   1  0     1

In [18]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [11]:
np.exp(-22) == np.exp(22)

False

In [12]:
weights = 2 * np.random.random((3,1)) - 1
weights

array([[ 0.44197007],
       [ 0.76964591],
       [-0.18681188]])

In [15]:
inputs = np.array(df[['x1', 'x2', 'bias']])
inputs

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]], dtype=int64)

In [21]:
correct_outputs = [[1], [1], [1], [0]]
correct_outputs

[[1], [1], [1], [0]]

In [24]:
for iterations in range(15000):
    weighted_sum = np.dot(inputs, weights)
    
    activated_output = sigmoid(weighted_sum)
    
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    weights += np.dot(inputs.T, adjustments)
    
print('Weights after training:', weights, '\n')

print('Output after training:', activated_output, '\n')

Weights after training: [[-9.58010802]
 [-9.58010802]
 [14.45535006]] 

Output after training: [[0.99999947]
 [0.99242449]
 [0.99242449]
 [0.00897004]] 



## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [25]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [32]:
diabetes['bias'] = 1
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  bias  
0                     0.627   50        1     1  
1                     0.351   31        0     1  
2                     0.672   32        1     1  
3                     0.167   21        0     1  
4                     2.288   33        1     1

In [34]:
df = diabetes[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
          'DiabetesPedigreeFunction', 'Age', 'bias', 'Outcome']]

In [35]:
df.shape

(768, 10)

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [55]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

# X = df.iloc[0:100, 0:-1].values
X = Normalizer.transform(array(df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
          'DiabetesPedigreeFunction', 'Age', 'bias']]))
X[:20]

NameError: name 'array' is not defined

In [40]:
weights = 2 * np.random.random((9,1)) - 1
print('Initial random weights:\n', weights)

Initial random weights:
 [[-0.87611636]
 [ 0.82853411]
 [ 0.33246885]
 [-0.76543557]
 [ 0.90132246]
 [ 0.70695112]
 [ 0.4915585 ]
 [ 0.6852461 ]
 [-0.54900277]]


In [42]:
y = np.array([[x] for x in df['Outcome']])
y[0:20]

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1]])

In [ ]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10000):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = __sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        self.weights = 2 * np.random.random((9,1)) - 1

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, self.weights)

            # Activate!
            activated_output = __sigmoid

            # Cac error

            # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

9

In [46]:
def fit(niter, X, y):
    weights = 2 * np.random.random((len(X[0]),1)) - 1
    for iterations in range(niter):
        weighted_sum = np.dot(X, weights)
        activated_output = sigmoid(weighted_sum)
        error = y - activated_output
        adjustments = error * sigmoid_derivative(weighted_sum)
        weights += np.dot(X.T, adjustments)
    return print('Weights after trianing:\n', weights, '\n\nOutput after trianing:\n', activated_output)

In [47]:
fit(10000, X, y)

ValueError: operands could not be broadcast together with shapes (768,1) (100,1) 

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?